### ISSUE TITLE
website attack logs never loads

### ISSUE THREAD

**Issue by deeztek** [ITSec-Chile/Waf2Py#9]
Trying to look at the attack logs on a particular website. All I see is a pacman animation and then eventually the following error appears on the top-right of the page:

![image](https://user-images.githubusercontent.com/17934095/52527569-a6681180-2c98-11e9-886b-789c7fc5d86a.png)

Reloading the page doesn't fix the issue.

**Comment by ch-rigu** [comment]
this was fixed in a previous commit [0266087](https://github.com/ITSec-Chile/Waf2Py/commit/026608747999b9e73594b28b51342175d83ab6b3)

I just did a clone now, I've replace the app and works fine.

![image](https://user-images.githubusercontent.com/40671439/52528099-ea1c4480-2cb3-11e9-8ea7-8f4330978396.png)

**Comment by deeztek** [comment]
I updated per the instructions below and the error still occurs:

git clone --branch waf2py_modsec3 --single-branch https://github.com/ITSec-Chile/Waf2Py.git
cd Waf2Py
unzip Waf2Py.zip
#Replace old app with new one
cp -r Waf2Py /home/www-data/waf2py_community/applications/
chown -R www-data.www-data /home/www-data/waf2py_community/applications/Waf2Py/

**Comment by ch-rigu** [comment]
you will have to check the error and post it here. 
Follow this steps:
go to: https://your_server_ip/admin and log in
there will be the waf2py app, click in "manage" button and select "errors", the click in "list by tickets" and click the first one, take a screenshot and post it here to see whats happening.

**Comment by deeztek** [comment]
Hi here's a screenshot:

![image](https://user-images.githubusercontent.com/17934095/52537204-e0d1bd00-2d31-11e9-9def-e68936329c53.png)

**Comment by ch-rigu** [comment]
thanks, please can you paste the hole tracebak ?

**Comment by ch-rigu** [comment]
i think i found the error (commit 001639a).
please make a pull , replace the app and try.

**Comment by deeztek** [comment]
I did a pull and replaced the app. Now all my websites are gone.

**Comment by ch-rigu** [comment]
is normal, you are replacing the whole app, including the database... juste create them again..
this week I will upload waf2py without be compressed, with a proper  git ignore and blablabla to avoid this kind of things things.

**Comment by deeztek** [comment]
Maybe normal but definitely annoying having to re-create 43 websites

**Comment by ch-rigu** [comment]
that's a lot, well this app is quite new, also nginx connector and modsec v3, you should test a bit more before to go in production with a lot of sites.....
There is a lot of features that will come in Waf2Py, and small modifications to the actual version.
Also feedback about if is working properly or not would be great (i have tested a lot and for me and some friend works fine), by now i just see people cloning or reporting bugs, without saying if is working good, something to improve etc...

**Comment by deeztek** [comment]
Hi, unfortunately the error remains. Here's the whole traceback:

![image](https://user-images.githubusercontent.com/17934095/52554422-c68cf300-2db4-11e9-85e3-6f7ff4da047a.png)

![image](https://user-images.githubusercontent.com/17934095/52554444-dad0f000-2db4-11e9-8dc2-dcdb80e2e8cd.png)
![image](https://user-images.githubusercontent.com/17934095/52554461-eb816600-2db4-11e9-98f7-e3e2e9e96897.png)

**Comment by deeztek** [comment]
I noticed something that looks strange to me in the modsecurity audit log config. It looks like two lines pointing to two different log types and logs. Is that right? Also even if my website configs were gone, it seems as if the old logs remain:

# Specify the path for concurrent audit logging.
#SecAuditLogType Concurrent
#SecAuditLogStorageDir /opt/waf/nginx/var/log/www.domain.tld/audit_logs
SecAuditLog /opt/waf/nginx/var/log/www.domain.tld/audit_logs/1_www.domain.tld_audit.log


# Use a single file for logging. This is much easier to look at, but
# assumes that you will use the audit log only ocassionally.
#
SecAuditLogType Serial
SecAuditLog /opt/waf/nginx/var/log/www.domain.tld/www.domain.tld_audit.log

**Comment by ch-rigu** [comment]
Now should be fixed, there was a problem in geoip when doesn't find the city, make a pull and to avoid lose your sites just replace this file /home/www-data/waf2py_community/applications/controllers/Logs.py with the new one in Waf2Py/controllers/Logs.py

Please comment if is working.

About the lines of modsec, this "SecAuditLog /opt/waf/nginx/var/log/www.domain.tld/audit_logs/1_www.domain.tld_audit.log" should be commented, this was part of the old waf2py with modsec 2.9.x. Anyway this doesn't affect logging of modsec (at least I haven't see trouble with the logs), because the value is updated in the next declaration.

Cheers.

**Comment by deeztek** [comment]
Hi, I am no longer getting the error clicking on the Attacks tab, however no logs are being displayed at all even though the the summary tab shows Critical Attacks. The configured modsecurity audit log file is completely empty. 

Thanks!

**Comment by deeztek** [comment]
After launching an attack to one of the websites in order to generate modsecurity audit logs, the error persists:

![image](https://user-images.githubusercontent.com/17934095/52651674-97f94000-2eba-11e9-9f4c-e53cf1c4fbc4.png)
![image](https://user-images.githubusercontent.com/17934095/52651693-a47d9880-2eba-11e9-8e29-1bdc732faa29.png)
![image](https://user-images.githubusercontent.com/17934095/52651717-b101f100-2eba-11e9-9d18-f6298b7f44df.png)

**Comment by ch-rigu** [comment]
oh i missed the key... is fixed now, please try again. 
make a pull and to avoid lose your sites just replace this file /home/www-data/waf2py_community/applications/controllers/Logs.py

about the empty logs, that's is something related nginx and modsecurity, when logs rotation come, he send the signal -USR1 this signal make nginx reopen his logs, and it work for all logs, except for  the audit_log, restarting nginx is the only way that I know  to recreate the audit log, by know to solve this you can just disable logration in the crontab or create a crontab that restart nginx after logratation script ends. 


I'm using log rotation with another python script to fill the "Download logs" view, every time logration ocurs  all logs rotated will appear here like in the image
![image](https://user-images.githubusercontent.com/40671439/52668455-5ab0a480-2ef2-11e9-9f7c-9cd43bc15e3b.png)

of course, this need to be improved but by now it does the job

**Comment by deeztek** [comment]
This seems to have fixed it. I had to zero out the logs with "cp /dev/null /opt/waf/nginx/var/log/www.domain.tld/www.domain.tld_audit.log" then I generated an attack and it was able to show the attack in the attacks tab. Even with the fixed Logs.py script it didn't seem to like the existing entries in the audit log so I had to start fresh.

**Comment by deeztek** [comment]
Sorry but it looks like it's back to getting that error. It seems to work for a bit but then it eventually screws up and start giving an error has occured. It almost seems like some entries are breaking the Attacks tab and some entries are fine.

**Comment by deeztek** [comment]
Here are the relevant logs:

![image](https://user-images.githubusercontent.com/17934095/52813042-ddf30700-3066-11e9-9f79-bc666a8d22b8.png)
![image](https://user-images.githubusercontent.com/17934095/52813064-ef3c1380-3066-11e9-8dd7-797111b943e8.png)
![image](https://user-images.githubusercontent.com/17934095/52813098-011db680-3067-11e9-88e8-f875e45c965e.png)

**Comment by ch-rigu** [comment]
Thanks, i'm gonna check whats happening

about the "cp /dev/null /opt/waf/nginx/var/log/www.domain.tld/www.domain.tld_audit.log", this workarond solve the issue with the empty audit_logs ?, I can implement something similar to fix this issue.

I have some questions about the performance, in other post you say that you have 43 websites, this is a lot..., all of them works fine whit this bundle ??
how are being consummed the resources? 
they are ok or is a  heavy load?

Cheers.

**Comment by ch-rigu** [comment]
Hi, i've fixed the issue, well i'm not facing this error so i'm dealing with this in blind. The problem was in city variable when is a Nonetype, I've putted some verifications when that happens.

Make a pull an replace Logs.py file
and about the performance, please can you share your experience with this bundle ?

**Comment by deeztek** [comment]
Hi, I installed the new Logs.py file and now when I click on an Application under the Dashboard it creates an Internal error. This error was created with the existing logs. Here are the details:

![image](https://user-images.githubusercontent.com/17934095/52847977-a1adbe00-30db-11e9-9049-415332af0e83.png)
![image](https://user-images.githubusercontent.com/17934095/52848018-b9854200-30db-11e9-8139-5af0b4790725.png)
![image](https://user-images.githubusercontent.com/17934095/52848045-cb66e500-30db-11e9-8945-30171f9bcf3e.png)
![image](https://user-images.githubusercontent.com/17934095/52848076-db7ec480-30db-11e9-8d59-2f477fbe1572.png)
![image](https://user-images.githubusercontent.com/17934095/52848109-edf8fe00-30db-11e9-9237-09e2878813f4.png)
![image](https://user-images.githubusercontent.com/17934095/52848137-ff420a80-30db-11e9-8981-84f335c7ef95.png)

**Comment by deeztek** [comment]
As far as performance and resources go here is a snapshot as of this morning:

**Ram Usage**
Total: 7977
Used: 1022
Free: 5016

**Swap Usage**
Total: 2047
Used: 0
Free: 2047

**Uptime**
04:47:31 up 4 days, 10:52,  1 user,  load average: 0.00, 0.04, 0.04

Top
![image](https://user-images.githubusercontent.com/17934095/52848678-4da3d900-30dd-11e9-9743-2f24b23f8e28.png)

**Comment by ch-rigu** [comment]
Hi, thanks for the information.

About the error, I forgot to mention that there's another file that you need to replace, that parser itself.
Replace the file under /home/www-data/waf2py_community/Waf2Py/static/is/parser_modsec3.js with the one in Waf2Py/static/is/parser_modsec3.js

Cheers.

**Comment by deeztek** [comment]
I replaced the parser_modsec3.js file as follows (I think there was a typo in your msg):

cp /Waf2Py/Waf2Py/static/js/parser_modsec3.js /home/www-data/waf2py_community/applications/Waf2Py/static/js

but I'm still getting an error:

![image](https://user-images.githubusercontent.com/17934095/52861975-0714a580-3102-11e9-996e-13b9d86fc560.png)
![image](https://user-images.githubusercontent.com/17934095/52862003-185db200-3102-11e9-8c7e-0839c9f481d9.png)

**Comment by ch-rigu** [comment]
Sorry there is another file that you need to replace, the summary view.
Replace /home/www-data/waf2py_community/Waf2Py/views/Logs/Summary.html with the one in Waf2Py/views/Logs/Summary.html

The best thing to avoid making this granular replacement is making a backup of the whole Waf2Py app in /home/www_data, then replace the app with the new one from git and then restore the database folder from your backup (/home/www-data/waf2py_community/Waf2Py/database/). With this you should have your sites again in the new version (as long you don't erase the sites in /opt/waf/ here is where the nginx and modsec resides)

Cheers

**Comment by ch-rigu** [comment]
I will make an script for this

**Comment by deeztek** [comment]
My directory structure seems to be different from what you are describing:

You said:
/home/www-data/waf2py_community/Waf2Py/database/

My structure is like this:
/home/www-data/waf2py_community/applications/Waf2Py/databases

**Comment by ch-rigu** [comment]
I just misspelled the paths...
